import AppKit
import Foundation

@MainActor
public final class ClipboardMonitor: ObservableObject {
    public static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int
    private let pasteboard: NSPasteboard
    private let storage: StorageManager

    // Sensitive pasteboard types to strictly ignore
    private static let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type")
    ]

    // Sensitive application bundle identifiers
    private static let sensitiveBundleIdentifiers: Set<String> = [
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword",
        "com.1password.1password",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.keychainaccess",
        "com.apple.Passwords"
    ]

    public init(
        pasteboard: NSPasteboard = .general,
        storage: StorageManager? = nil
    ) {
        self.pasteboard = pasteboard
        self.storage = storage ?? .shared
        self.lastChangeCount = pasteboard.changeCount
    }

    public func startMonitoring(interval: TimeInterval = 0.3) {
        stopMonitoring()
        lastChangeCount = pasteboard.changeCount

        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.checkForChanges()
            }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    public func checkForChanges() {
        let currentChangeCount = pasteboard.changeCount
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount

        // 1. Check for sensitive types
        if isSensitivePasteboard() {
            return
        }

        // 2. Check frontmost application
        let frontApp = NSWorkspace.shared.frontmostApplication
        let bundleId = frontApp?.bundleIdentifier
        if let bundleId = bundleId, Self.sensitiveBundleIdentifiers.contains(bundleId) {
            return
        }

        // 3. Extract text content
        guard let text = pasteboard.string(forType: .string) else { return }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }

        // 4. Save to history
        storage.add(content: text, sourceAppBundle: bundleId)
    }

    /// Check if the pasteboard has concealed, auto-generated, or transient markers
    public func isSensitivePasteboard() -> Bool {
        guard let types = pasteboard.types else { return false }
        for type in types {
            if Self.sensitiveTypes.contains(type) {
                return true
            }
        }
        return false
    }

    /// Copies an item back to pasteboard, advancing change count so we don't duplicate
    public func copyToPasteboard(item: ClipItem) {
        pasteboard.clearContents()
        pasteboard.setString(item.content, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }
}
